# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
      - refs/heads/*
    exclude:
      - refs/tags/*
  paths:
    exclude:
      - README.md
      - LICENSE
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md

variables:
  image: 'macOS-latest'
  xCode: '11'

jobs:
  - job: DangerSwiftLint
    continueOnError: true
    pool:
      vmImage: $(image)
    steps:
      - bash: |
          brew install swiftlint ; brew install danger/tap/danger-swift ; export DANGER_GITHUB_API_TOKEN='$(DANGER_GITHUB_API_TOKEN)' ; danger-swift ci 
        displayName: 'Danger SwiftLint'

  - job: PodInstall
    dependsOn: DangerSwiftLint
    condition: succeeded()
    pool:
      vmImage: $(image)
    steps:
      - bash: |
          sh pod_install.sh
        displayName: 'Installing cocoapods'

  - job: PodLint
    dependsOn: PodInstall
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: $(image)
    steps:
      - bash: |
          pod lib lint --skip-tests
        displayName: 'Lint pod library'

  - job: Build
    dependsOn: PodInstall
    condition: succeeded()
    pool:
      vmImage: $(image)
    steps:
      - task: Xcode@5
        displayName: 'Build Xcode App'
        inputs:
          actions: 'build'
          sdk: 'iphonesimulator'
          scheme: 'Tests'
          configuration: 'Debug'
          xcWorkspacePath: 'Tests/Tests.xcworkspace'
          xcodeVersion: $(xCode)
          packageApp: false

  - job: Test
    dependsOn: Build
    condition: succeeded()
    pool:
      vmImage: $(image)
    steps:
      - task: Xcode@5
        displayName: 'Running tests'
        inputs:
          actions: 'test'
          sdk: 'iphonesimulator'
          configuration: 'Debug'
          xcWorkspacePath: 'Tests/Tests.xcworkspace'
          scheme: 'TestsTests'
          xcodeVersion: $(xCode)
          publishJUnitResults: true
          destinationPlatformOption: 'iOS'
          destinationTypeOption: 'simulators'
          destinationSimulators: 'iPhone 8'
      - bash: |
          cd Tests & bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
        displayName: 'Upload coverage to codecov.io'
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/junit.xml'
        displayName: 'Publish tests results'
